name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs at midnight every day
  workflow_dispatch: # Allows manual run
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ParvathyM155
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_lines: yes
